version: "3.1"

services:
  backend:
    image: postgres
    restart: always
    environment:
      DB_HOST: ""
      DB_USER: ""
      DB_PASS: ""
      DB_DATABASE: ""
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
