version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "hackaton"
    ports:
      - 5432:5432
    networks:
      - net_hackaton

  back_end:
    build: .
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - net_hackaton

networks:
  net_hackaton:
    driver: bridge
